### TeamMeng valid
POST http://localhost:6688/user/create
Content-Type: application/json

{
    "phone": "13877778888",
    "nickname": "TeamMeng",
    "password": "hunter42"
}

### TeamAlice valid
POST http://localhost:6688/user/create
Content-Type: application/json

{
    "phone": "13877778889",
    "nickname": "TeamAlice",
    "password": "hunter42"
}

### phone invalid
POST http://localhost:6688/user/create
Content-Type: application/json

{
    "phone": "3877778888",
    "nickname": "TeamMeng",
    "password": "hunter42"
}

### TeamMeng signin valid
POST http://localhost:6688/user/signin
Content-Type: application/json

{
    "phone": "13877778889",
    "password": "hunter42"
}

### TeamAlice signin valid
POST http://localhost:6688/user/signin
Content-Type: application/json

{
    "phone": "13877778888",
    "password": "hunter42"
}

### signin invalid
POST http://localhost:6688/user/signin
Content-Type: application/json

{
    "phone": "13877778888",
    "password": "123456"
}

### get all users
GET http://localhost:6688/user/users

### create followee
POST http://localhost:6688/follower/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODkxNTYsImV4cCI6MTc0MDQ5Mzk1NiwibmJmIjoxNzM5ODg5MTU2LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkSzFIUnlIZ2k4cWpnUlR4Q0RiMVNpUSQvRlZWM3BCeDlFRzdsaGV3Qi9tQitEOE5UbTZGazJrenc3M1h0MHV2L2dRIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTQ6MzI6MzAuNzM3NDc4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMwLjczNzQ3OFoifQ.aIoRlacATDeEZYbrLmLikq2zawGETEoo6kb3OlW7jftj8frrYVLDIyMafP0edwyZtvIHBGwCOPAWnpGT3qudAg

{
    "followee": 2
}

### get follower
GET http://localhost:6688/follower/geter
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODkxNTYsImV4cCI6MTc0MDQ5Mzk1NiwibmJmIjoxNzM5ODg5MTU2LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkSzFIUnlIZ2k4cWpnUlR4Q0RiMVNpUSQvRlZWM3BCeDlFRzdsaGV3Qi9tQitEOE5UbTZGazJrenc3M1h0MHV2L2dRIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTQ6MzI6MzAuNzM3NDc4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMwLjczNzQ3OFoifQ.aIoRlacATDeEZYbrLmLikq2zawGETEoo6kb3OlW7jftj8frrYVLDIyMafP0edwyZtvIHBGwCOPAWnpGT3qudAg

### get followee
GET http://localhost:6688/follower/getee
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODkxNTYsImV4cCI6MTc0MDQ5Mzk1NiwibmJmIjoxNzM5ODg5MTU2LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkSzFIUnlIZ2k4cWpnUlR4Q0RiMVNpUSQvRlZWM3BCeDlFRzdsaGV3Qi9tQitEOE5UbTZGazJrenc3M1h0MHV2L2dRIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTQ6MzI6MzAuNzM3NDc4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMwLjczNzQ3OFoifQ.aIoRlacATDeEZYbrLmLikq2zawGETEoo6kb3OlW7jftj8frrYVLDIyMafP0edwyZtvIHBGwCOPAWnpGT3qudAg

### delete follower
DELETE http://localhost:6688/follower/delete/2
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODY2MjgsImV4cCI6MTc0MDQ5MTQyOCwibmJmIjoxNzM5ODg2NjI4LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkWXpJa2JrTlVOamV4RmNocEVOZ2d4dyR2dWt1a0JYY3lnQWdCSGpqUUhyT29HWGF4Mi9HamZGTFk3M0VVUXdoSHFzIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTM6NTA6MjEuMTI3ODMyWiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDEzOjUwOjIxLjEyNzgzMloifQ.JMZjNkM7Y3NVLC-Oifg-1zFQOBkl0W9qaZLe7B4zBHTOf6RW5Os5vxM8aZMLE-cLhvDfh22oExvBVEfwhHXpDw

### create post
POST http://localhost:6688/post/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODkxNTYsImV4cCI6MTc0MDQ5Mzk1NiwibmJmIjoxNzM5ODg5MTU2LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkSzFIUnlIZ2k4cWpnUlR4Q0RiMVNpUSQvRlZWM3BCeDlFRzdsaGV3Qi9tQitEOE5UbTZGazJrenc3M1h0MHV2L2dRIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTQ6MzI6MzAuNzM3NDc4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMwLjczNzQ3OFoifQ.aIoRlacATDeEZYbrLmLikq2zawGETEoo6kb3OlW7jftj8frrYVLDIyMafP0edwyZtvIHBGwCOPAWnpGT3qudAg

{
    "content": "Hello World"
}

### get all post
GET http://localhost:6688/post/get/1

### get post
GET http://localhost:6688/post/get/1/4

### delete post
DELETE http://localhost:6688/post/delete/4
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk4ODkxNTYsImV4cCI6MTc0MDQ5Mzk1NiwibmJmIjoxNzM5ODg5MTU2LCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoxLCJuaWNrbmFtZSI6IlRlYW1NZW5nIiwicGhvbmUiOiIxMzg3Nzc3ODg4OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTE5NDU2LHQ9MixwPTEkSzFIUnlIZ2k4cWpnUlR4Q0RiMVNpUSQvRlZWM3BCeDlFRzdsaGV3Qi9tQitEOE5UbTZGazJrenc3M1h0MHV2L2dRIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMThUMTQ6MzI6MzAuNzM3NDc4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMwLjczNzQ3OFoifQ.aIoRlacATDeEZYbrLmLikq2zawGETEoo6kb3OlW7jftj8frrYVLDIyMafP0edwyZtvIHBGwCOPAWnpGT3qudAg

### get feeds
GET http://localhost:6688/feed/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5NTgyNDAsImV4cCI6MTc0MDU2MzA0MCwibmJmIjoxNzM5OTU4MjQwLCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoyLCJuaWNrbmFtZSI6IlRlYW1BbGljZSIsInBob25lIjoiMTM4Nzc3Nzg4ODkiLCJwYXNzd29yZF9oYXNoIjoiJGFyZ29uMmlkJHY9MTkkbT0xOTQ1Nix0PTIscD0xJDg3STdwMTdTUklHUFlUSzE3SVNTUnckcTJZWnZZOUUreXU4elJ5YjJndXdPaG9BSlkvZnN1M3lyYXFUL2kxdmN4ZyIsImNyZWF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMyLjY2NzQ1MFoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMi0xOFQxNDozMjozMi42Njc0NTBaIn0.ThxJyFfhsyqKhLOKn_y67NHR4crm9GXtMwctOb4eV9PJtzEaE-1AP5jtaQ6DmmsJfm6E3j-fYzwGYEJuNqyzAQ

{
    "pid": 5,
    "size": 1
}

### like
POST http://localhost:6688/like/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5NTgyNDAsImV4cCI6MTc0MDU2MzA0MCwibmJmIjoxNzM5OTU4MjQwLCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoyLCJuaWNrbmFtZSI6IlRlYW1BbGljZSIsInBob25lIjoiMTM4Nzc3Nzg4ODkiLCJwYXNzd29yZF9oYXNoIjoiJGFyZ29uMmlkJHY9MTkkbT0xOTQ1Nix0PTIscD0xJDg3STdwMTdTUklHUFlUSzE3SVNTUnckcTJZWnZZOUUreXU4elJ5YjJndXdPaG9BSlkvZnN1M3lyYXFUL2kxdmN4ZyIsImNyZWF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMyLjY2NzQ1MFoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMi0xOFQxNDozMjozMi42Njc0NTBaIn0.ThxJyFfhsyqKhLOKn_y67NHR4crm9GXtMwctOb4eV9PJtzEaE-1AP5jtaQ6DmmsJfm6E3j-fYzwGYEJuNqyzAQ

{
    "pid": 5
}

### get all like
GET http://localhost:6688/like/get/5

### delete like
DELETE http://localhost:6688/like/delete/5
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5NTgyNDAsImV4cCI6MTc0MDU2MzA0MCwibmJmIjoxNzM5OTU4MjQwLCJpc3MiOiJhY2NvdW50X3NlcnZlciIsImF1ZCI6ImFjY291bnRfd2ViIiwidWlkIjoyLCJuaWNrbmFtZSI6IlRlYW1BbGljZSIsInBob25lIjoiMTM4Nzc3Nzg4ODkiLCJwYXNzd29yZF9oYXNoIjoiJGFyZ29uMmlkJHY9MTkkbT0xOTQ1Nix0PTIscD0xJDg3STdwMTdTUklHUFlUSzE3SVNTUnckcTJZWnZZOUUreXU4elJ5YjJndXdPaG9BSlkvZnN1M3lyYXFUL2kxdmN4ZyIsImNyZWF0ZWRfYXQiOiIyMDI1LTAyLTE4VDE0OjMyOjMyLjY2NzQ1MFoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMi0xOFQxNDozMjozMi42Njc0NTBaIn0.ThxJyFfhsyqKhLOKn_y67NHR4crm9GXtMwctOb4eV9PJtzEaE-1AP5jtaQ6DmmsJfm6E3j-fYzwGYEJuNqyzAQ
