### valid
POST http://localhost:6688/user/create
Content-Type: application/json

{
    "phone": "13877778888",
    "nickname": "TeamMeng",
    "password": "hunter42"
}

### phone invalid
POST http://localhost:6688/user/create
Content-Type: application/json

{
    "phone": "3877778888",
    "nickname": "TeamMeng",
    "password": "hunter42"
}

### signin valid
POST http://localhost:6688/user/signin
Content-Type: application/json

{
    "phone": "13877778888",
    "password": "hunter42"
}

### signin invalid
POST http://localhost:6688/user/signin
Content-Type: application/json

{
    "phone": "13877778888",
    "password": "123456"
}
